# Generated by Django 2.2 on 2019-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwd',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('passwd', models.TextField()),
            ],
        ),
    ]
